name: CD Pipeline

on:
  push:
    branches: [main]

jobs:
  # ------------------------------------------
  # Job 1: Build & Push Back-end Docker Image
  # ------------------------------------------
  deploy-backend:
    name: Push Back-end
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push back-end Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./BIDZ/back-end
          file: ./BIDZ/back-end/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bidz-backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # ------------------------------------------
  # Job 2: Build & Push Front-end Docker Image
  # ------------------------------------------
  deploy-frontend:
    name: Push Front-end
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: BIDZ/Front-end/package-lock.json

      - name: Install dependencies
        working-directory: ./BIDZ/Front-end
        run: npm install --legacy-peer-deps

      - name: Run ESLint
        working-directory: ./BIDZ/Front-end
        run: npm run lint

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push front-end Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./BIDZ/Front-end
          file: ./BIDZ/Front-end/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bidz-frontend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
